### ISSUE TITLE
Install UnicodeDecodeError on Win10

### ISSUE THREAD

**Issue by dyj9999** [machow/siuba#341]
```
(base) C:\WINDOWS\system32>pip install siuba
Collecting siuba
  Using cached https://files.pythonhosted.org/packages/5c/5c/26953e9eb2dfe85cf7ea759db945705961546dbde27102eaa6c1ba71cb66/siuba-0.0.25.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AppData\Local\Temp\pip-install-nrabacgd\siuba\setup.py", line 14, in <module>
        README = f.read()
      File "D:\Software\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 533: character maps to <undefined>

Command "python setup.py egg_info" failed with error code 1 in C:\Users\AppData\Local\Temp\pip-install-nrabacgd\siuba\
```

Anyone knows how to solve this? Thanks!

**Comment by machow** [comment]
Hey, sorry, this is mentioned in #336 . I can try implementing the fix mentioned there to see if it resolves in the next day or two

**Comment by machow** [comment]
Should be resolved
