### ISSUE TITLE
Install verion 1.0.0a2  DecodeError

### ISSUE THREAD

**Issue by antonio-yu** [machow/siuba#369]
`>pip install siuba==1.0.0a2`

```
ERROR: Command errored out with exit status 1:
     command: 'D:\programfiles\anaconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yuliang18\\AppData\\Local\\Temp\\pip-install-mcv70u9g\\siuba_417389fde0d6404f8ec80b6c6d8fdacc\\setup.py'"'"'; __file__='"'"'C:\\Users\\yuliang18\\AppData\\Local\\Temp\\pip-install-mcv70u9g\\siuba_417389fde0d6404f8ec80b6c6d8fdacc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\yuliang18\AppData\Local\Temp\pip-pip-egg-info-jtd_gv03'
         cwd: C:\Users\yuliang18\AppData\Local\Temp\pip-install-mcv70u9g\siuba_417389fde0d6404f8ec80b6c6d8fdacc\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\yuliang18\AppData\Local\Temp\pip-install-mcv70u9g\siuba_417389fde0d6404f8ec80b6c6d8fdacc\setup.py", line 14, in <module>
        README = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 3058: illegal multibyte sequence
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/4a/f4/94b5238d5194179dd6849081a47078989d2fac624bf3aa23757d369e6bab/siuba-1.0.0a2.tar.gz#sha256=7a5016166969a2d97845009681939fe0b6841932e2d8783046a311394666230c (from https://pypi.tuna.tsinghua.edu.cn/simple/siuba/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement siuba==1.0.0a2
ERROR: No matching distribution found for siuba==1.0.0a2
```

**Comment by machow** [comment]
Sorry--let me push a fix up now. I think this is the piece needed:

https://github.com/machow/siuba/issues/336

**Comment by machow** [comment]
should be resolved--thanks for flagging, definitely let me know if you hit issues installing 1.0.0a3
